// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: pb/user/user-find.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserFindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sort    int64  `protobuf:"zigzag64,1,opt,name=sort,proto3" json:"sort,omitempty"`
	Page    int64  `protobuf:"zigzag64,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage int64  `protobuf:"zigzag64,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Status  string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Search  string `protobuf:"bytes,5,opt,name=search,proto3" json:"search,omitempty"`
}

func (x *UserFindRequest) Reset() {
	*x = UserFindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_user_user_find_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserFindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFindRequest) ProtoMessage() {}

func (x *UserFindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_user_user_find_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFindRequest.ProtoReflect.Descriptor instead.
func (*UserFindRequest) Descriptor() ([]byte, []int) {
	return file_pb_user_user_find_proto_rawDescGZIP(), []int{0}
}

func (x *UserFindRequest) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *UserFindRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *UserFindRequest) GetPerPage() int64 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *UserFindRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserFindRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type UserFind struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users   []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Rows    int64   `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Pages   int64   `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	PerPage int64   `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Total   int64   `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *UserFind) Reset() {
	*x = UserFind{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_user_user_find_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserFind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFind) ProtoMessage() {}

func (x *UserFind) ProtoReflect() protoreflect.Message {
	mi := &file_pb_user_user_find_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFind.ProtoReflect.Descriptor instead.
func (*UserFind) Descriptor() ([]byte, []int) {
	return file_pb_user_user_find_proto_rawDescGZIP(), []int{1}
}

func (x *UserFind) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *UserFind) GetRows() int64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *UserFind) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *UserFind) GetPerPage() int64 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *UserFind) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UserFindResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsEmpty bool      `protobuf:"varint,1,opt,name=is_empty,json=isEmpty,proto3" json:"is_empty,omitempty"`
	Payload *UserFind `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *UserFindResponse) Reset() {
	*x = UserFindResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_user_user_find_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserFindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFindResponse) ProtoMessage() {}

func (x *UserFindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_user_user_find_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFindResponse.ProtoReflect.Descriptor instead.
func (*UserFindResponse) Descriptor() ([]byte, []int) {
	return file_pb_user_user_find_proto_rawDescGZIP(), []int{2}
}

func (x *UserFindResponse) GetIsEmpty() bool {
	if x != nil {
		return x.IsEmpty
	}
	return false
}

func (x *UserFindResponse) GetPayload() *UserFind {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_pb_user_user_find_proto protoreflect.FileDescriptor

var file_pb_user_user_find_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x62, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2d, 0x66,
	0x69, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x62, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x84, 0x01,
	0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x12, 0x52,
	0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x12, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x65, 0x72,
	0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x12, 0x52, 0x07, 0x70, 0x65, 0x72,
	0x50, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x22, 0x82, 0x01, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x46, 0x69, 0x6e,
	0x64, 0x12, 0x1b, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x05, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x6f,
	0x77, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x65, 0x72, 0x5f,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x70, 0x65, 0x72, 0x50,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x52, 0x0a, 0x10, 0x55, 0x73, 0x65,
	0x72, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x69, 0x73, 0x5f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x69, 0x73, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x23, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x46, 0x69, 0x6e, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x09, 0x5a,
	0x07, 0x70, 0x62, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_user_user_find_proto_rawDescOnce sync.Once
	file_pb_user_user_find_proto_rawDescData = file_pb_user_user_find_proto_rawDesc
)

func file_pb_user_user_find_proto_rawDescGZIP() []byte {
	file_pb_user_user_find_proto_rawDescOnce.Do(func() {
		file_pb_user_user_find_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_user_user_find_proto_rawDescData)
	})
	return file_pb_user_user_find_proto_rawDescData
}

var file_pb_user_user_find_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_user_user_find_proto_goTypes = []interface{}{
	(*UserFindRequest)(nil),  // 0: UserFindRequest
	(*UserFind)(nil),         // 1: UserFind
	(*UserFindResponse)(nil), // 2: UserFindResponse
	(*User)(nil),             // 3: User
}
var file_pb_user_user_find_proto_depIdxs = []int32{
	3, // 0: UserFind.users:type_name -> User
	1, // 1: UserFindResponse.payload:type_name -> UserFind
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_user_user_find_proto_init() }
func file_pb_user_user_find_proto_init() {
	if File_pb_user_user_find_proto != nil {
		return
	}
	file_pb_user_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_user_user_find_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserFindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_user_user_find_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserFind); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_user_user_find_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserFindResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_user_user_find_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_user_user_find_proto_goTypes,
		DependencyIndexes: file_pb_user_user_find_proto_depIdxs,
		MessageInfos:      file_pb_user_user_find_proto_msgTypes,
	}.Build()
	File_pb_user_user_find_proto = out.File
	file_pb_user_user_find_proto_rawDesc = nil
	file_pb_user_user_find_proto_goTypes = nil
	file_pb_user_user_find_proto_depIdxs = nil
}
